[package]
name = "animur"
version = "0.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

[lib]
name = "animur"
path = "src/lib/lib.rs"

[[bin]]
name = "cracker"
path = "src/main/main.rs"

[dependencies]
byteorder = "^1.3"
structopt = "^0.3"